### ISSUE TITLE
Registering service provider twice

### ISSUE THREAD

**Issue by arrilot** [tpetry/laravel-postgresql-enhanced#1]
Hi, I've checked the source code and I see that your service provider extends `Illuminate\Database\DatabaseServiceProvider` and calls `parent::regitser` 

As a result `Illuminate\Database\DatabaseServiceProvider;` is registered twice
Are you sure this approach has no logic and performace drawbacks?

**Comment by tpetry** [comment]
The extension of the DatabaseServiceProvider is from an old attempt and is really not required anymore. It doesn't cause any performance penalty since it just overwrites the bindings already registered by the DatabaseServiceProvider with the same ones again, but I'll fix it anyway. Thanks for the hint.

**Comment by tpetry** [comment]
I still have a long way to go for (almost) full PostgreSQL support. Anything you are currently missing?

**Comment by arrilot** [comment]
> Anything you are currently missing?
Nothing yet. Keep up the great work!

Really loved your package, gonna try it next well.
