### ISSUE TITLE
How to create a JsonB/Json Index on a specific field?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [tpetry/laravel-postgresql-enhanced#16]
This database engine does not support JSON operations.
So I guess it just is not supported in Laravel yet?

```
  at vendor/laravel/framework/src/Illuminate/Database/Grammar.php:137
    133▕      * @throws \RuntimeException
    134▕      */
    135▕     protected function wrapJsonSelector($value)
    136▕     {
  ➜ 137▕         throw new RuntimeException('This database engine does not support JSON operations.');
    138▕     }

```

```
data = {
  query: 'some text here'
}
```

```php
$table->index('data ->>query', 'IX_some_query')->algorithm('gin')->with(['fastupdate' => false]);
$table->index('((data->>‘hobbies’))', 'idx_yep')->algorithm('BTREE');
```

**Comment by tpetry** [comment]
You are currently not using this package as described in #14. Therefore none of the feature I built are available to you, you need to fix your setup first.

Please stop creating new issues until you solved #14. You are just creating new issues again and again because you are effectively not using this package!
