### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by beeyev** [tpetry/laravel-postgresql-enhanced#49]
Firstly, thank you so much for the great package, I have been using it for quite a long, and it's absolutely great.

I have a question, since Laravel 10 will be released very soon, on February 7th. Will this package support the new Laravel version?

**Comment by tpetry** [comment]
Laravel 10 will definetely be supported. I'll do the needed changes after Laracon EU. So next week ;)

**Comment by tpetry** [comment]
I almost finished the Laravel 10 support. But I am currently blocked by laravel/framework#45907 which I found while running my tests against the new version. Currently the new version behaves differently. I maybe could workaround that in my implementation, but I will first wait whether it may be fixed in Laravel 10.

**Comment by tpetry** [comment]
Version `0.26.0` is compatible with Laravel `6.x` up to `10.x`.
