### ISSUE TITLE
Support for lateral join on query builder

### ISSUE THREAD

**Issue by vigneshgurusamy** [tpetry/laravel-postgresql-enhanced#9]
We love your work and titbits on twitter.

Recently, we had an usecase to implement lateral join in laravel. Since it is specific to Postgres grammar, we used raw query to implement in our project.

Do you have any plan to extend postgres query builder in future? For example: lateral join with query builder.

**Comment by tpetry** [comment]
Thanks for the feedback ❤️

I am open to almost any feature anyone may need. Lateral joins are a nice feature and I am using them too and needed to go back to raw queries. But they are not as easy to implement.

I currently see two possible ways of adding them:
1. I add the `joinSubLateral`, `leftJoinSubLateral`, `rightJoinSubLateral` and `crossJoinSubLateral` methods
2. I check whether my pull request to Laravel 9 for [improved query expressions](https://github.com/laravel/framework/pull/40115) can be used to implement lateral joins.

I, personally, would prefer the second case with an API like the following, but I have to check whether this will really work:
```php
$subquery = DB::table('table2)->...();

DB::table('table')
  ->joinSub(new LateralQuery($subquery))
  ->...();
```

**Comment by tpetry** [comment]
I really liked the idea of supporting lateral subquery joins as I am using them too. Query expressions did not work because of how laravel does encapsulate subqueries. 

I've added `crossJoinSubLateral`, `joinSubLateral` and `leftJoinSubLateral`. Each one has the same behavior as their Laravel counterparts, but now they are lateral subquery joins.
