### ISSUE TITLE
Fatal error: Declaration of Tpetry\PostgresqlEnhanced\Query\BuilderWhere::orWhereLike

### ISSUE THREAD

**Issue by vatsake** [tpetry/laravel-postgresql-enhanced#99]
After updating laravel/framework v11.4.0 => v11.23.5

```
In BuilderWhere.php line 67:
                                                                                                                                              
  Declaration of Tpetry\PostgresqlEnhanced\Query\BuilderWhere::orWhereLike($column, $value, bool $caseInsensitive = false): static must be compatible with Illuminate\Database\Query\Builder::orWhereLike($column, $value, $caseSensitive = false)   
```

**Comment by tpetry** [comment]
With Laravel 11 this library has to be upgraded to the stable v1 version. The old 0.x versions don't work anymore.

I finally release a stable release to better communicate breaking changes because of conflicts with Laravel - like here: The `orWhereLike` method I introduced long ago has been introduced with Laravel 11.17.0 too. But with a different method signature.
